
packages = ["Pillow"]

[[fetch]]
from = "."
files = [
    "action_panel.png",
    "arcadeclassic.regular.ttf",
    "background.png",
    "battle_bg.png",
    "blaster_warning.png",
    "boldpixels.boldpixels.ttf",
    "bubble.png",
    "button.png",
    "button_hover.png",
    "DTM-Mono.otf",
    "DTM-Sans.otf",
    "fight_bar.png",
    "fight_target.png",
    "fish.png",
    "fish2.png",
    "fish2_flipped.png",
    "fish3.png",
    "fish3_flipped.png",
    "fish4.png",
    "fish4_flipped.png",
    "fishing_bg.png",
    "fishing_target.png",
    "fish_flipped.png",
    "gameover_bg.png",
    "ice.png",
    "kelp.png",
    "kelpcam.png",
    "miku_fish.png",
    "miku_fish_flipped.png",
    "orca_battle.png",
    "proj_bone.png",
    "proj_bubble.png",
    "proj_wave.png",
    "seal.png",
    "sleep.png",
    "soul.png",
    "sparkle.png",
    "stats_panel.png",
    "stat_energy_0.png",
    "stat_energy_100.png",
    "stat_energy_25.png",
    "stat_energy_50.png",
    "stat_energy_75.png",
    "stat_happiness_0.png",
    "stat_happiness_100.png",
    "stat_happiness_25.png",
    "stat_happiness_50.png",
    "stat_happiness_75.png",
    "stat_health_0.png",
    "stat_health_100.png",
    "stat_health_25.png",
    "stat_health_50.png",
    "stat_health_75.png",
    "stat_hunger_0.png",
    "stat_hunger_100.png",
    "stat_hunger_25.png",
    "stat_hunger_50.png",
    "stat_hunger_75.png",
    "title_panel.png",
    "tycoon_icon_aquarium.png",
    "tycoon_icon_base.png",
    "tycoon_icon_boat.png",
    "tycoon_icon_bucket.png",
    "tycoon_icon_drone.png",
    "tycoon_icon_moon.png",
    "tycoon_icon_pearl.png",
    "tycoon_icon_penguin.png",
    "tycoon_icon_research.png",
    "tycoon_icon_satellite.png",
    "tycoon_icon_skill.png",
    "tycoon_icon_upgrade.png",
    "ui_act.png",
    "ui_act_selected.png",
    "ui_fight.png",
    "ui_fight_selected.png",
    "ui_item.png",
    "ui_item_selected.png",
    "ui_mercy.png",
    "ui_mercy_selected.png",
    "victory_bg.png",
    "wave.png",
    "main.py",
    "cmu_graphics.py",
]